do not load rspec task if no rspec available
On production appliances, rspec gem is not installed
This was causing an error like:

```
rake aborted!
NameError: uninitialized constant RSpec
/var/www/miq/vmdb/lib/tasks/spec_evm.rake:10:in block (2 levels) in <top (required)>'
/var/www/miq/vmdb/lib/tasks/spec_evm.rake:2:inblock in '
/var/www/miq/vmdb/lib/tasks/spec_evm.rake:1:in <top (required)>'
/var/www/miq/vmdb/Rakefile:8:in'
/var/www/miq/vmdb/script/rake:15:in <top (required)>'
/var/www/miq/vmdb/script/rails:6:inrequire'
/var/www/miq/vmdb/script/rails:6:in `'
(See full trace by running task with --trace)
```