drop_from_selection needs to be method of PivotOptions
Addressing:
Error caught: [NoMethodError] undefined method `drop_from_selection' for #<ReportController::PivotOptions>
app/controllers/report_controller/reports/editor.rb:940:in `block in move_cols_left'
app/controllers/report_controller/reports/editor.rb:930:in `each'
app/controllers/report_controller/reports/editor.rb:930:in `move_cols_left'
app/controllers/report_controller/reports/editor.rb:529:in `gfv_move_cols_buttons'
app/controllers/report_controller/reports/editor.rb:395:in `get_form_vars'
app/controllers/report_controller/reports/editor.rb:116:in `form_field_changed'