Use ruby and require config/environment instead of rails runner.
The primary use cases for rails runner are for
* quick in-line ruby evaluation such as `rails runner 'puts User.first.name'`
* shebang line at the top of executables

While it supports passing the path to a ruby script, it leads to weird
errors if the file is not found for any reason:

`$ bin/rails r "/home/joe/run.rb"`
  => `unknown regexp option - j (SyntaxError)`

`$ bin/rails r "joe/run.rb"`
  => `undefined local variable or method `joe' for main:Object (NameError)`

Since this is NOT the typical use case for rails runner, it's safer to
use ruby to load our launcher and require config/environment in the
launcher.

A nice side effect is $PROGRAM_NAME can be reliably used to detect what
type of worker the current process is:
`manageiq/lib/workers/bin/evm_server.rb`