collect_children now support's has_ones by returning them as an array.
Callers of collect_children expect arrays.

Fixes:

```
undefined method `empty?' for #<Host:0x007f9dbdbd9dd8>
  /~/.gem/ruby/2.2.4/gems/activemodel-4.2.5.1/lib/active_model/attribute_methods.rb:433:in `method_missing'
  ./app/models/condition.rb:165:in `_subst_find'
```