Use concrete EMS for testing providers api
The API now returns emstype_description which is not available for base
class ExtManagementSystem.

Addressing:
undefined method `description' for #<Class:0x0056318fc517c0>
  lib/active_record/dynamic_matchers.rb:21:in `method_missing',
  app/models/ext_management_system.rb:338:in `emstype_description'