BootstrapSelect - use global jQuery
to make sure selectpicker is there, even when global jQuery comes from bower
this means we now depend on global jquery + bootstrap-select, but works in master and gaprindashvili

---

Fixes

	miq_debug.self-a72dc0b9f690f63b4688fbca3774709918c11fdfb7b5fc454690d11d007fc88b.js?body=1:29 TypeError: m(...).selectpicker is not a function
		at t.value (BootstrapSelect.js:29)
		at commitLifeCycles (react-dom.production.min.js:159)