Spec should not stub out DatabaseBackup._gc
We need to stub actuall db backup implementation, but we should not stub
much more. After this change spec fails and uncovers

  [NameError]: undefined local variable or method `current_db_opts' for #<Class:0x0000000ce6fa30>
  in app/models/database_backup.rb:66:in `_gc'

That issue is now known as https://bugzilla.redhat.com/show_bug.cgi?id=1343586